name: Contest Reminder

on:
  issues: 
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # LOL.. Normally the whole task exceute faster than cancellation.
#     - name: Cancel if unrelated issue
#       if: "!contains(${{ github.event.issue.title }}, 'CReminder Trigger')"
#       uses: andymckay/cancel-action@0.2
#       with:
#         token: ${{ github.token }}
    
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: |
        if [[ "${{ github.event.issue.title }}" == *"CReminder Trigger"* ]]; then
          mvn -B package --file pom.xml
        else
          echo "Skipping Build Jar"
        fi
    
    - name: Hourly Checks
      run: |
        if [[ "${{ github.event.issue.title }}" == *"HOURLY"* ]]; then
          java -jar target/creminder-1.0.jar ${{ secrets.SENDER_EMAIL }} ${{ secrets.APP_PASSWORDS }} ${{ secrets.RECEIVER_EMAIL }} ${{ secrets.ZONE_ID }} hourly
        else
          echo "Skipping Send Hourly Email"
        fi

    - name: Daily Checks
      run:  |
        if [[ "${{ github.event.issue.title }}" == *"DAILY"* ]]; then
          java -jar target/creminder-1.0.jar ${{ secrets.SENDER_EMAIL }} ${{ secrets.APP_PASSWORDS }} ${{ secrets.RECEIVER_EMAIL }} ${{ secrets.ZONE_ID }} daily
        else
          echo "Skipping Send Daily Email"
        fi
  
