# Sends reminder everyday at 5PM Asia/Dhaka time. Change the time on line 7 to your needs.
name: Java CI with Maven

on:
  issues: 
    types: [opened]

    concurrency:
      group: ${{ github.event.issue.title }}
      cancel-in-progress: ${{ github.event.issue.title != '*CReminder Trigger*' }}
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
#     - name: Cancel if unrelated issue
#       if: "!contains(${{ github.event.issue.title }}, 'CReminder Trigger')"
#     - uses: andymckay/cancel-action@0.2
    
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        if [[ "${{ github.event.issue.title }}" == *"CReminder Trigger"* ]]; then
          mvn -B package --file pom.xml
        else
          echo "Skipping Build Jar"
        fi
    
#     - name: Hourly Checks
#       if: "contains(${{ github.event.issue.title}}, 'HOURLY')"
#       run: script for condition 1

    - name: Daily Checks
#       if: "contains(${{ github.event.issue.title}}, 'DAILY')"
      run:  |
        if [[ "${{ github.event.issue.title }}" == *"DAILY"* ]]; then
          java -jar target/creminder-1.0.jar ${{ secrets.SENDER_EMAIL }} ${{ secrets.APP_PASSWORDS }} ${{ secrets.RECEIVER_EMAIL }} ${{ secrets.ZONE_ID }} daily
        else
          echo "Skipping Send Daily Email"
        fi
    - name: Debug
      run: echo "${{ github.event.issue.title }}"
  
